name: Build FBX Wheels (Linux)

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      python: "3.7"
                      py: "37"
                      platform: manylinux_2_28_x86_64

                    - os: ubuntu-latest
                      python: "3.9"
                      py: "39"
                      platform: manylinux_2_28_x86_64

                    - os: ubuntu-latest
                      python: "3.11"
                      py: "311"
                      platform: manylinux_2_28_x86_64

                    - os: ubuntu-latest
                      python: "3.13"
                      py: "313"
                      platform: manylinux_2_28_x86_64

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v7

            - name: Restore FBX SDK and FBX Python bindings cache
              id: cache-fbx
              uses: actions/cache@v6
              with:
                  path: |
                      cache
                  key: fbx-2020.3.9-${{ runner.os }}

            - name: Clear all *.whl files in the cache folder
              if: always()
              run: |
                  rm -f cache/**/*.whl

            - name: Install FBX SDK and FBX Python bindings
              run: |
                  python scripts/install_fbx.py

            - name: Enable PEP 484 type stubs
              run: |
                  python scripts/enable_hints.py

            - name: Build and test wheels
              uses: pypa/cibuildwheel@v2.21.0
              # Use version compatible with Python 3.7
              with:
                  package-dir: "cache/fbxbind"
              env:
                  CIBW_BUILD: "cp${{ matrix.py }}-manylinux_x86_64"
                  CIBW_SKIP: "*-manylinux_i686 *-musllinux_* pp*"
                  CIBW_TEST_SKIP: "cp313-*"
                  CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_28"
                  CIBW_BUILD_VERBOSITY: "1"
                  CIBW_BEFORE_BUILD: "pip install --force-reinstall sip==6.6.2"
                  CIBW_ENVIRONMENT: "FBXSDK_ROOT=/project/cache/fbxsdk"
                  CIBW_BEFORE_ALL_LINUX: "yum install -y gcc-c++ make zlib-devel libxml2-devel"
                  CIBW_TEST_COMMAND: >
                      python -c "import fbx; import os; print(os.path.dirname(fbx.__file__))" && 
                      python {project}/scripts/test.py -o {project}/test_output

            - name: Upload wheels
              uses: actions/upload-artifact@v7
              if: success() || failure()
              with:
                  name: fbx-2020.3.9-py${{ matrix.python }}-${{ matrix.platform }}
                  path: wheelhouse/*.whl
                  if-no-files-found: ignore
