name: Build FBX Wheels (Windows)

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: windows-latest
                      python: "3.7"
                      platform: win_amd64

                    - os: windows-latest
                      python: "3.9"
                      platform: win_amd64

                    - os: windows-latest
                      python: "3.11"
                      platform: win_amd64

                    - os: windows-latest
                      python: "3.13"
                      platform: win_amd64

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-python@v6
              with:
                  python-version: ${{ matrix.python }}

            - name: Show build target
              run: |
                  python --version
                  echo Platform: ${{ matrix.platform }}

            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install sip==6.6.2

            - name: Restore FBX SDK and FBX Pythpn bindings cache
              id: cache-fbx
              uses: actions/cache@v6
              with:
                  path: |
                      cache
                  key: fbx-2020.3.9-${{ runner.os }}

            - name: Clear all *.whl files in the cache folder
              if: always()
              shell: bash
              run: |
                  rm -f cache/**/*.whl

            - name: Install FBX SDK and FBX Python bindings
              run: |
                  python scripts/install_fbx.py

            - name: Build wheel
              run: |
                  python scripts/build.py

            - name: Install wheel
              shell: bash
              run: |
                  python -m pip install ./dist/*.whl

            - name: Upload wheel
              uses: actions/upload-artifact@v6
              with:
                  name: fbx-2020.3.9-py${{ matrix.python }}-${{ matrix.platform }}
                  path: dist/*.whl

            - name: Test wheel
              shell: pwsh
              run: |
                  python -c "import fbx; import os; print(os.path.dirname(fbx.__file__))"
                  $env:FBXSDK_ROOT = "${{ github.workspace }}\cache\fbxsdk"
                  python scripts/test.py -o "${{ runner.temp }}\test_output" --ascii
                  Write-Host "Success: $?"
                  Write-Host "Exit code: $LASTEXITCODE"
