name: Build FBX Wheels (Windows)

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: windows-latest
                      python: "3.7"
                      py: "37"
                      platform: win_amd64

                    - os: windows-latest
                      python: "3.9"
                      py: "39"
                      platform: win_amd64

                    - os: windows-latest
                      python: "3.11"
                      py: "311"
                      platform: win_amd64

                    - os: windows-latest
                      python: "3.13"
                      py: "313"
                      platform: win_amd64

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v6

            - name: Set up specific MSVC Toolset
              uses: ilammy/msvc-dev-cmd@v1
              with:
                  arch: x64
                  toolset: "14.44"

            - name: Restore FBX SDK and FBX Python bindings cache
              id: cache-fbx
              uses: actions/cache@v6
              with:
                  path: |
                      cache
                  key: fbx-2020.3.9-${{ runner.os }}

            - name: Clear all *.whl files in the cache folder
              if: always()
              shell: bash
              run: |
                  rm -f cache/**/*.whl

            - name: Install FBX SDK and FBX Python bindings
              run: |
                  python scripts/install_fbx.py

            - name: Enable PEP 484 type stubs
              run: |
                  python scripts/enable_hints.py

            - name: Build and test wheels
              uses: pypa/cibuildwheel@v2.21.0
              # Use version compatible with Python 3.7
              with:
                  package-dir: "cache/fbxbind"
              env:
                  CIBW_BUILD: "cp${{ matrix.py }}-win_amd64"
                  CIBW_SKIP: "-win32 *arm64 pp*"
                  CIBW_TEST_SKIP: "cp313-*"
                  CIBW_BUILD_VERBOSITY: "1"
                  CIBW_BEFORE_BUILD: "pip install --force-reinstall sip==6.6.2"
                  CIBW_ENVIRONMENT: >
                      DISTUTILS_USE_SDK=1
                      MSSdk=1
                      FBXSDK_ROOT=../fbxsdk
                      FBXSDK_COMPILER=vs2022
                  CIBW_TEST_COMMAND: >
                      python -c "import fbx; import os; print(os.path.dirname(fbx.__file__))" && 
                      python %GITHUB_WORKSPACE%/scripts/test.py -o %GITHUB_WORKSPACE%/test_output

            - name: Upload wheels
              uses: actions/upload-artifact@v7
              if: success() || failure()
              with:
                  name: fbx-2020.3.9-py${{ matrix.python }}-${{ matrix.platform }}
                  path: wheelhouse/*.whl
                  if-no-files-found: ignore
